# This file contains the default labels for the repository.
- name: bug
  color: "d73a4a"
  description: "Something isn't working"

- name: duplicate
  color: "cfd3d7"
  description: "This issue or pull request already exists"

- name: eligible for internship
  color: "a2eeef"
  description: "Suitable issues for interns"

- name: enhancement
  color: "a2eeef"
  description: "New feature or request"

- name: documentation
  color: "007acc"
  description: "Related to project documentation"

- name: good first issue
  color: "7057ff"
  description: "Good for newcomers"

- name: help wanted
  color: "008672"
  description: "Extra attention is needed"

- name: invalid
  color: "e4e669"
  description: "This doesn't seem right"

- name: question
  color: "d876e3"
  description: "Further information is requested"

- name: urgent
  color: "e99695"
  description: "Tasks that need to be done very soon to fulfill deadlines or stopping other tasks."

- name: wontfix
  color: "ffffff"
  description: "This will not be worked on"
