// Test pin definitions for IoTempower
// Generated by extracting IOT_TEST_ constants from pins.h

#ifndef _IOTEMPOWER_TESTDEFS_H_
#define _IOTEMPOWER_TESTDEFS_H_

#define IOT_TEST_INPUT 0
#define IOT_TEST_OUTPUT 16
#define IOT_TEST_DIGITAL 15
#define IOT_TEST_DIGITAL_2 13
#define IOT_TEST_NEOPIXEL_CONTROL_METHOD NeoEsp32I2s0Ws2812xMethod
#define IOT_TEST_NEOPIXEL_TESTPIN 16
#endif // _IOTEMPOWER_TESTDEFS_H_
