#!/usr/bin/env bash
# This file might be not executable as is (for example when run in Termux on
# Android). This file is best run as: bash run
# (after changing into this ulnoiot directory)
#
# At first start it installs the local ulnoiot-environment
#
# Author: ulno
# Create date: 2017-05-17
#
# if parameters are given and the first is "exec", ulnoiot will execute
# the rest of the parameters as command in ulnoiot environment

function welcome() {
cat << EOF
ulnoiot
=======

Your friendly and affordable Internet of Things environment.
More at http://iot.ulno.net

EOF
}

function check_files() {
    for file in "$@"; do
        if [ ! -e "$file" ]; then
            echo "Can't find $file."
            return 1
        fi
    done
    return 0
}


function check_root() {
    if [ -e "$ULNOIOT_ROOT/lib/shell_starter/ulnoiot.bash" ]; then
        cd "$ULNOIOT_ROOT"
    fi
    # else we should assume that we were started from the root-directory
    #echo -n "Checking now that we are in the ulnoiot root directory. "
    check_files "lib/shell_starter/ulnoiot.bash" \
        "bin/shebang_run" \
        "etc/ulnoiot.conf.example"
    if [ $? -ne 0 ]; then
        echo
        echo "Cannot find ulnoiot files."
        echo "Stopping now."
        return 1
    fi

    # Yes, found them.
    echo
    return 0
}

function check_install() {
    # Check if all local directories and paths have been set up
    check_files .local/bin/shebang_run .local/vp/bin/activate
    return $?
}

function install() {
    echo "Installing now."
    echo
    bash "$ULNOIOT_ROOT/bin/install"
}


function run() {
    if [ "$1" = "exec" ]; then
        shift
        exec "$@"
    else
        exec bash
    fi
}


######## Main #########
welcome
current_path="$(pwd)" # save to restore later
if check_root; then
    export ULNOIOT_ROOT=$(realpath "$(pwd)")
    source "$ULNOIOT_ROOT/lib/shell_starter/ulnoiot.bash" \
        || { echo "Can't read configuration. Aborting."; exit 1; }
    check_install
    cd "$current_path" # back to where we have been called
    if [ $? -eq 0 ]; then
        run "$@"
    else
        if install; then # if it failed, try to install first
            run "$@"
        fi
    fi
fi
