// Test pin definitions for IoTempower
// Generated by extracting IOT_TEST_ constants from pins.h

#ifndef _IOTEMPOWER_TESTDEFS_H_
#define _IOTEMPOWER_TESTDEFS_H_

#define IOT_TEST_INPUT D3
#define IOT_TEST_OUTPUT D4
#define IOT_TEST_DIGITAL D1
#define IOT_TEST_DIGITAL_2 D2
#define IOT_TEST_NEOPIXEL_CONTROL_METHOD NeoEsp8266Uart1800KbpsMethod
#define IOT_TEST_NEOPIXEL_TESTPIN 2

#endif // _IOTEMPOWER_TESTDEFS_H_
