// Test pin definitions for IoTempower
// Generated by extracting IOT_TEST_ constants from pins.h

#ifndef _IOTEMPOWER_TESTDEFS_H_
#define _IOTEMPOWER_TESTDEFS_H_

#define IOT_TEST_INPUT BUTTON_HOME
#define IOT_TEST_OUTPUT ONBOARDLED
#define IOT_TEST_DIGITAL 26
#define IOT_TEST_DIGITAL_2 36

#endif // _IOTEMPOWER_TESTDEFS_H_
