#define IOT_TEST_INPUT FLASHBUTTON
#define IOT_TEST_OUTPUT 2
#define IOT_TEST_DIGITAL 9
#define IOT_TEST_DIGITAL_2 13
#define IOT_TEST_NEOPIXEL_CONTROL_METHOD NeoEsp8266Uart1800KbpsMethod
#define IOT_TEST_NEOPIXEL_TESTPIN 2