#define IOT_TEST_INPUT FLASHBUTTON
#define IOT_TEST_OUTPUT ONBOARDLED
#define IOT_TEST_DIGITAL 26
#define IOT_TEST_DIGITAL_2 36
#define IOT_TEST_NEOPIXEL_CONTROL_METHOD NeoEsp32I2s0Ws2812xMethod
#define IOT_TEST_NEOPIXEL_TESTPIN 26
