// Test pin definitions for IoTempower
// Generated by extracting IOT_TEST_ constants from pins.h

#ifndef _IOTEMPOWER_TESTDEFS_H_
#define _IOTEMPOWER_TESTDEFS_H_

#define IOT_TEST_INPUT FLASHBUTTON
#define IOT_TEST_OUTPUT ONBOARDLED
#define IOT_TEST_DIGITAL 26

#endif // _IOTEMPOWER_TESTDEFS_H_
