#define IOT_TEST_INPUT 17
#define IOT_TEST_OUTPUT 16
#define IOT_TEST_DIGITAL 15
#define IOT_TEST_DIGITAL_2 13
#define IOT_TEST_NEOPIXEL_CONTROL_METHOD NeoEsp32I2s0Ws2812xMethod
#define IOT_TEST_NEOPIXEL_TESTPIN 16
