#define IOT_TEST_INPUT BUTTON1
#define IOT_TEST_OUTPUT 13
#define IOT_TEST_DIGITAL D10
#define IOT_TEST_DIGITAL_2 4
#define IOT_TEST_NEOPIXEL_CONTROL_METHOD NeoEsp8266Uart1800KbpsMethod
#define IOT_TEST_NEOPIXEL_TESTPIN 2