// Test pin definitions for IoTempower
// Generated by extracting IOT_TEST_ constants from pins.h

#ifndef _IOTEMPOWER_TESTDEFS_H_
#define _IOTEMPOWER_TESTDEFS_H_

#define IOT_TEST_INPUT BUTTON1
#define IOT_TEST_OUTPUT 13
#define IOT_TEST_DIGITAL D10
#define IOT_TEST_DIGITAL_2 4

#endif // _IOTEMPOWER_TESTDEFS_H_
