#!/data/data/com.termux/files/usr/bin/bash

dir=$(cd -P -- "$(dirname -- "$0")" && pwd -P)
cd "$dir"

ulnoiot mqtt_broker &
mqttid=$!

# let mqtt start
sleep 3

ulnoiot mqtt_action pipe07/wsens01/water onechange 1 "$dir/do_alarm" &
actionid=$!

echo "Press return to continue."
read tmp

kill $mqttid $actionid
pkill -f mqtt_broker
pkill mosquitto
