#!/data/data/com.termux/files/usr/bin/bash

dir=$(cd -P -- "$(dirname -- "$0")" && pwd -P)
cd "$dir"

play-audio -s alarm \
    "$dir/248211__jomellejager__alarm-1.m4a" &

termux-notification --priority high \
    --title "Water Sensor 1 Report" \
    --content "high levels detected" \
    --vibrate 500,200,500,200,500,200,500 \
    --led-color ff0000 \
    --led-off 250 \
    --led-on 500 \
    --action "termux-toast Water message dismissed" \
    --button1 "React" \
    --button1-action "termux-toast Thanks for taking care."

