#!/bin/bash

PACKAGE_LIST="curl git base-devel mosquitto python-virtualenv rsync haveged jq nodejs npm"
to_install=$(filter_packages arch-query $PACKAGE_LIST)

echo "Installing: $to_install..."
arch-install $to_install
echo "Installation of $to_install complete."

# curl git mosquitto python-virtualenv rsync haveged jq # general
# ./arch-install iptables bridge-utils hostapd dnsmasq # router and networking

# ./arch-install mc micro # this is optional: mc is nicer file management in cli, micro a nicer editor than nano

# sudo systemctl stop mosquitto
# sudo systemctl disable mosquitto


#     #   install_package_if_missing "apt-utils"
#     #   install_package_if_missing "make"
#     #   install_package_if_missing "git"
#     #   install_package_if_missing "python3.11-venv"
#     #   install_package_if_missing "python3-dev"
#     #   install_package_if_missing "gcc-aarch64-linux-gnu"
#     #   install_package_if_missing "jq"
#     #   install_package_if_missing "haveged"

# # install node.js

#     curl -fsSL https://deb.nodesource.com/setup_21.x | bash - && apt-get install -y nodejs
