#!/bin/bash

PACKAGE_LIST="mosquitto"
to_install=$(filter_packages debian-query $PACKAGE_LIST)

echo "Installing: $to_install..."
arch-install $to_install
echo "Installation of $to_install complete."

# TODO: ask if this should be done?
sudo systemctl stop mosquitto
sudo systemctl disable mosquitto


