#!/usr/bin/env bash

# check caddy version
installed_version=$(caddy -v &> /dev/null| sed 's/v//') # Remove the 'v' prefix from version

if [[ -z "$installed_version" ]]; then
    installed_version="0.0.0-notinstalled"
fi

# Define the minimum required version
min_version="2.5"

# Use sort with version sort flag to compare versions, and check the first line
if [[ "$installed_version" && "$(printf "%s\n%s" "$min_version" "$installed_version" | sort -V | head -n1)" = "$min_version" ]]; then
    echo "Caddy version is higher or equal than the minimum required version $min_version."
    exit 0
else
    echo "Caddy version $installed_version is installed, it does not meet the minimum required version $min_version."
    # install current caddy
    echo "Installing: $to_install..."
    debian-install debian-keyring debian-archive-keyring apt-transport-https
    curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' | \
        sudo gpg --dearmor --yes -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
    curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' | \
        sudo tee /etc/apt/sources.list.d/caddy-stable.list
    debian-update
    debian-install caddy
    # is started on old ubuntus
    sudo systemctl stop caddy
    sudo systemctl disable caddy
    echo "Installation of $to_install complete."
fi


