#!/usr/bin/env bash

# TODO: potentially also install sudo?

# check if sudo is installed
if ! debian-query sudo > /dev/null; then
    echo "sudo is not installed, no packages can be installed."
    echo "Either install all dependencies yourself or install sudo"
    echo "and add yourself to the sudo group."
    echo "Lots of error messages will potentially follow."
    echo
    exit 1
fi

# check if curl is installed
if ! debian-query curl > /dev/null; then
    echo "curl is not installed, installing. Please wait..."
    debian-install curl
    # check error and return 1 if not found
    if [[ $? != 0 ]]; then
        echo "curl could not be installed, exiting now."
        exit 1
    fi
    echo "curl has been installed successfully"
fi

# # on native debian gateway, we want network-manager <- TODO!
# # connect to network
# apt update
# apt upgrade
# apt install network-manager sudo
# apt purge ifupdown
# usermod -aG sudo iot # assuming iot user was created during install
# # TODO: verify sshd is installed and enbaled
# should also adjust /etc/systemd/logind.conf to prevent sleeping when lid closed

# procps allows pkill and ps
PACKAGE_LIST="build-essential git procps mosquitto-clients virtualenv python3-venv python3-dev make rsync openssh-client haveged jq"
to_install=$(filter_packages debian-query $PACKAGE_LIST)

echo "Installing: $to_install..."
debian-install $to_install
echo "Installation of $to_install complete."

# curl git mosquitto python-virtualenv rsync haveged jq # general
# ./arch-install iptables bridge-utils hostapd dnsmasq # router and networking

if command -v systemctl > /dev/null; then # docker does not have systemctl
    sudo systemctl stop mosquitto
    sudo systemctl disable mosquitto
fi

exit 0