#!/usr/bin/env bash

# TODO: potentially also install sudo?

# check if sudo is installed
if ! fedora-query sudo > /dev/null; then
    echo "sudo is not installed, no packages can be installed."
    echo "Either install all dependencies yourself or install sudo"
    echo "and add yourself to the sudo group."
    echo "Lots of error messages will potentially follow."
    echo
    exit 1
fi

# check if curl is installed
if ! fedora-query curl > /dev/null; then
    echo "curl is not installed, installing. Please wait..."
    fedora-install curl
    # check error and return 1 if not found
    if [[ $? != 0 ]]; then
        echo "curl could not be installed, exiting now."
        exit 1
    fi
    echo "curl has been installed successfully"
fi

# procps allows pkill and ps
PACKAGE_LIST="gcc gcc-c++ make git procps virtualenv python3-virtualenv python3-devel make rsync openssh-client haveged jq"
to_install=$(filter_packages fedora-query $PACKAGE_LIST)

echo "Installing: $to_install..."
fedora-install $to_install
echo "Installation of $to_install complete."

# curl git mosquitto python-virtualenv rsync haveged jq # general
# ./arch-install iptables bridge-utils hostapd dnsmasq # router and networking
exit 0