#!/bin/env bash

# TODO: What about tealdir ipython xonsh darkhttpd
PACKAGE_LIST="mc micro tilde tmux"
to_install=$(filter_packages termux-query $PACKAGE_LIST)

echo "Installing: $to_install..."
termux-install $to_install
echo "Installation of $to_install complete."


