#!/bin/env bash
if command -v caddy >/dev/null; then
    if apt list 2>/dev/null|grep '\[installed'|grep -q caddy; then
        echo "Caddy is installed"
        exit 0
    fi
else
    echo "Caddy is not installed, installing"
fi

termux-install caddy
