// Test pin definitions for IoTempower
// Generated by extracting IOT_TEST_ constants from pins.h

#ifndef _IOTEMPOWER_TESTDEFS_H_
#define _IOTEMPOWER_TESTDEFS_H_

#define IOT_TEST_INPUT 0
#define IOT_TEST_OUTPUT RELAIS
#define IOT_TEST_DIGITAL 1
#define IOT_TEST_DIGITAL_2 3
#endif // _IOTEMPOWER_TESTDEFS_H_
