#define IOT_TEST_INPUT 0
#define IOT_TEST_OUTPUT RELAIS
#define IOT_TEST_DIGITAL 1
#define IOT_TEST_DIGITAL_2 3
#define IOT_TEST_NEOPIXEL_CONTROL_METHOD NeoEsp8266Uart1800KbpsMethod
#define IOT_TEST_NEOPIXEL_TESTPIN 2
