#!/bin/bash
# Example script for starting ulnoiot
# Modify ULNOIOT_ROOT accordingly to your setup
#
# If you run in termux, apply termux-fix shebang onto this script

export ULNOIOT_ROOT="$HOME/ulnoiot"
ulnoiot=""
if [ "$1" ]; then
    ulnoiot="ulnoiot"
fi
exec bash "$ULNOIOT_ROOT/run" $ulnoiot "$@"
