---
name: Compilation Tests

'on':
  pull_request:
    branches: [master, main]
    paths:
      - 'lib/**'
      - 'tests/**'
      - 'bin/**'
      - 'examples/**'
      - '.github/workflows/compilation-tests.yml'
  workflow_dispatch:
    inputs:
      boards:
        description: >-
          Comma-separated list of boards to test
          (default: wemos_d1_mini,esp32minikit)
        required: false
        default: 'wemos_d1_mini,esp32minikit'
      devices:
        description: >-
          Comma-separated list of devices to test
          (default: input,output,analog)
        required: false
        default: 'input,output,analog'

jobs:
  compilation-test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        # Test key boards separately for parallel execution
        board: [wemos_d1_mini, esp32minikit]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup IoTempower environment
        run: |
          # Copy repository to ~/iot for testing
          cp -r . ~/iot

      - name: Run compilation tests
        run: |
          # Determine which boards and devices to test
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            BOARDS="${{ github.event.inputs.boards }}"
            DEVICES="${{ github.event.inputs.devices }}"
          else
            # Default subset for PR tests
            BOARDS="${{ matrix.board }}"
            DEVICES="input,output,analog"
          fi

          echo "Testing boards: $BOARDS"
          echo "Testing devices: $DEVICES"

          # Run tests using the recommended approach
          cat ~/iot/bin/curl_install_docker | IOTEMPOWER_REPO=~/iot bash -s -- test compilation --boards=$BOARDS --devices=$DEVICES

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: compilation-test-results-${{ matrix.board }}
          path: ~/iot-container/
          retention-days: 7
